/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2018-09-27 19:02:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Swift_002dFront_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\" >\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <title>SwiftIndex</title>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("      <link rel=\"stylesheet\" href=\"resources/style/style.css\">\r\n");
      out.write("      <!-- <link rel=\"text/javascript\" href=\"resources/js/main.js\"> -->\r\n");
      out.write("      \r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var request;\r\n");
      out.write("var bnk;\r\n");
      out.write("\r\n");
      out.write("function sendInfo() {\r\n");
      out.write("    //var v=document.country.id;\r\n");
      out.write("    var url=\"coindex.jsp\";\r\n");
      out.write("\r\n");
      out.write("    if(window.XMLHttpRequest){\r\n");
      out.write("        request=new XMLHttpRequest();\r\n");
      out.write("    }\r\n");
      out.write("    try {\r\n");
      out.write("        request.onreadystatechange=getInfo;\r\n");
      out.write("        request.open(\"GET\",url,true);\r\n");
      out.write("        request.send();\r\n");
      out.write("    }\r\n");
      out.write("    catch(e) {\r\n");
      out.write("        alert(\"Unable to connect to server\");\r\n");
      out.write("    }\r\n");
      out.write("    //getInfo();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function getInfo() {\r\n");
      out.write("    if(request.readyState==4){\r\n");
      out.write("        var val = JSON.parse(request.responseText);\r\n");
      out.write("        var i;\r\n");
      out.write("        var sel = document.getElementById('country');\r\n");
      out.write("        var Sel = document.getElementById('Country');\r\n");
      out.write("         for(i in val){\r\n");
      out.write("            var option = document.createElement(\"option\");\r\n");
      out.write("            var Option = document.createElement(\"option\");\r\n");
      out.write("            option.text = val[i].country_name;\r\n");
      out.write("            Option.text = val[i].country_name;\r\n");
      out.write("            //option.id  = val[i].country_code;\r\n");
      out.write("            sel.add(option);\r\n");
      out.write("            Sel.add(Option);\r\n");
      out.write("           }\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function updateBank(e) {\r\n");
      out.write("\tvar selVal = e.value;\r\n");
      out.write("    var url=\"coindex.jsp?val=\"+selVal+\"&type=\"+e.id;\r\n");
      out.write("    request=new XMLHttpRequest();\r\n");
      out.write("    try {\r\n");
      out.write("        \tif(e.id == \"country\")\r\n");
      out.write("        \t\trequest.onreadystatechange=getInfoBank;\r\n");
      out.write("        \tif(e.id == \"Country\")\r\n");
      out.write("        \t\trequest.onreadystatechange=getInfoBankk;\r\n");
      out.write("\t\t\tif(e.id == \"bank\"){\r\n");
      out.write("\t\t\t\trequest.onreadystatechange=getInfoCity;\r\n");
      out.write("\t\t\t\tbnk = e.value;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(e.id == \"Bank\"){\r\n");
      out.write("\t\t\t\trequest.onreadystatechange=getInfoCityy;\r\n");
      out.write("\t\t\t\tbnk = e.value;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(e.id == \"city\"){\r\n");
      out.write("\t\t\t\trequest.onreadystatechange=getInfoBranch;\r\n");
      out.write("\t\t\t\turl = url + \"&bank=\"+bnk;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(e.id == \"City\"){\r\n");
      out.write("\t\t\t\trequest.onreadystatechange=getInfoBranchh;\r\n");
      out.write("\t\t\t\turl = url + \"&bank=\"+bnk;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(e.id == \"branch\"){\r\n");
      out.write("\t\t\t\trequest.onreadystatechange=getInfoSwift;\r\n");
      out.write("\t\t\t\turl = url + \"&bank=\"+bnk;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(e.id == \"Branch\"){\r\n");
      out.write("\t\t\t\trequest.onreadystatechange=getInfoSwiftt;\r\n");
      out.write("\t\t\t\turl = url + \"&bank=\"+bnk;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("        request.open(\"GET\",url,true);\r\n");
      out.write("        request.send();\r\n");
      out.write("    }\r\n");
      out.write("    catch(e) {\r\n");
      out.write("        alert(\"Unable to connect to server\"+e);\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("//First select\r\n");
      out.write("function getInfoBank() {\r\n");
      out.write("    if(request.readyState==4){\r\n");
      out.write("        var val = JSON.parse(request.responseText);\r\n");
      out.write("        var i;\r\n");
      out.write("        var sel = document.getElementById('bank');\r\n");
      out.write("        while (sel.hasChildNodes()) {  \r\n");
      out.write("            sel.removeChild(sel.firstChild);\r\n");
      out.write("        }\r\n");
      out.write("        var opt = document.createElement(\"option\");\r\n");
      out.write("        opt.text = \"Select a Bank\";\r\n");
      out.write("        sel.add(opt);\r\n");
      out.write("         for(i in val){\r\n");
      out.write("            var option = document.createElement(\"option\");\r\n");
      out.write("            option.text = val[i].bank_name;\r\n");
      out.write("            //option.id  = val[i].country_code;\r\n");
      out.write("            sel.add(option);\r\n");
      out.write("           }\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function getInfoCity() {\r\n");
      out.write("    if(request.readyState==4){\r\n");
      out.write("        var val = JSON.parse(request.responseText);\r\n");
      out.write("        var i;\r\n");
      out.write("        var sel = document.getElementById('city');\r\n");
      out.write("        while (sel.hasChildNodes()) {  \r\n");
      out.write("            sel.removeChild(sel.firstChild);\r\n");
      out.write("        }\r\n");
      out.write("        var opt = document.createElement(\"option\");\r\n");
      out.write("        opt.text = \"Select a City\";\r\n");
      out.write("        sel.add(opt);\r\n");
      out.write("         for(i in val){\r\n");
      out.write("            var option = document.createElement(\"option\");\r\n");
      out.write("            option.text = val[i].city_name;\r\n");
      out.write("            //option.id  = val[i].country_code;\r\n");
      out.write("            sel.add(option);\r\n");
      out.write("           }\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function getInfoBranch() {\r\n");
      out.write("    if(request.readyState==4){\r\n");
      out.write("        var val = JSON.parse(request.responseText);\r\n");
      out.write("        var i;\r\n");
      out.write("        var sel = document.getElementById('branch');\r\n");
      out.write("        while (sel.hasChildNodes()) {  \r\n");
      out.write("            sel.removeChild(sel.firstChild);\r\n");
      out.write("        }\r\n");
      out.write("        var opt = document.createElement(\"option\");\r\n");
      out.write("        opt.text = \"Select a Branch\";\r\n");
      out.write("        sel.add(opt);\r\n");
      out.write("//        alert(sel);\r\n");
      out.write("         for(i in val){\r\n");
      out.write("            var option = document.createElement(\"option\");\r\n");
      out.write("            option.text = val[i].branch_name;\r\n");
      out.write("            //option.id  = val[i].country_code;\r\n");
      out.write("            sel.add(option);\r\n");
      out.write("           }\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function getInfoSwift() {\r\n");
      out.write("    if(request.readyState==4){\r\n");
      out.write("        var val = JSON.parse(request.responseText);\r\n");
      out.write("        //alert(val[0].swift_code);\r\n");
      out.write("        var option = document.createElement(\"option\");\r\n");
      out.write("        var sel = document.getElementById(\"swiftcode\");\r\n");
      out.write("        while (sel.hasChildNodes()) {  \r\n");
      out.write("            sel.removeChild(sel.firstChild);\r\n");
      out.write("        }\r\n");
      out.write("        option.text = val[0].swift_code;\r\n");
      out.write("        sel.add(option);\r\n");
      out.write("           \r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//End of First\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function getInfoBankk() {\r\n");
      out.write("    if(request.readyState==4){\r\n");
      out.write("        var val = JSON.parse(request.responseText);\r\n");
      out.write("        var i;\r\n");
      out.write("        var sel = document.getElementById('Bank');\r\n");
      out.write("        while (sel.hasChildNodes()) {  \r\n");
      out.write("            sel.removeChild(sel.firstChild);\r\n");
      out.write("        }\r\n");
      out.write("        var opt = document.createElement(\"option\");\r\n");
      out.write("        opt.text = \"Select a Bank\";\r\n");
      out.write("        sel.add(opt);\r\n");
      out.write("         for(i in val){\r\n");
      out.write("            var option = document.createElement(\"option\");\r\n");
      out.write("            option.text = val[i].bank_name;\r\n");
      out.write("            //option.id  = val[i].country_code;\r\n");
      out.write("            sel.add(option);\r\n");
      out.write("           }\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function getInfoCityy() {\r\n");
      out.write("    if(request.readyState==4){\r\n");
      out.write("        var val = JSON.parse(request.responseText);\r\n");
      out.write("        var i;\r\n");
      out.write("        var sel = document.getElementById('City');\r\n");
      out.write("        while (sel.hasChildNodes()) {  \r\n");
      out.write("            sel.removeChild(sel.firstChild);\r\n");
      out.write("        }\r\n");
      out.write("        var opt = document.createElement(\"option\");\r\n");
      out.write("        opt.text = \"Select a City\";\r\n");
      out.write("        sel.add(opt);\r\n");
      out.write("         for(i in val){\r\n");
      out.write("            var option = document.createElement(\"option\");\r\n");
      out.write("            option.text = val[i].city_name;\r\n");
      out.write("            //option.id  = val[i].country_code;\r\n");
      out.write("            sel.add(option);\r\n");
      out.write("           }\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function getInfoBranchh() {\r\n");
      out.write("    if(request.readyState==4){\r\n");
      out.write("        var val = JSON.parse(request.responseText);\r\n");
      out.write("        var i;\r\n");
      out.write("        var sel = document.getElementById('Branch');\r\n");
      out.write("        while (sel.hasChildNodes()) {  \r\n");
      out.write("            sel.removeChild(sel.firstChild);\r\n");
      out.write("        }\r\n");
      out.write("        var opt = document.createElement(\"option\");\r\n");
      out.write("        opt.text = \"Select a Branch\";\r\n");
      out.write("        sel.add(opt);\r\n");
      out.write("//        alert(sel);\r\n");
      out.write("         for(i in val){\r\n");
      out.write("            var option = document.createElement(\"option\");\r\n");
      out.write("            option.text = val[i].branch_name;\r\n");
      out.write("            //option.id  = val[i].country_code;\r\n");
      out.write("            sel.add(option);\r\n");
      out.write("           }\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function getInfoSwiftt() {\r\n");
      out.write("    if(request.readyState==4){\r\n");
      out.write("        var val = JSON.parse(request.responseText);\r\n");
      out.write("        //alert(val[0].swift_code);\r\n");
      out.write("        var option = document.createElement(\"option\");\r\n");
      out.write("        var sel = document.getElementById(\"Swiftcode\");\r\n");
      out.write("        while (sel.hasChildNodes()) {  \r\n");
      out.write("            sel.removeChild(sel.firstChild);\r\n");
      out.write("        }\r\n");
      out.write("        option.text = val[0].swift_code;\r\n");
      out.write("        sel.add(option);\r\n");
      out.write("        //document.getElementById(\"Swiftcode\").text = val[0].swift_code;\r\n");
      out.write("           \r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("  \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body onload=\"sendInfo()\">\r\n");
      out.write("\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("\t<div class=\"bird-container bird-container--one\">\r\n");
      out.write("\t\t<div class=\"bird bird--one\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"bird-container bird-container--two\">\r\n");
      out.write("\t\t<div class=\"bird bird--two\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"bird-container bird-container--three\">\r\n");
      out.write("\t\t<div class=\"bird bird--three\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"bird-container bird-container--four\">\r\n");
      out.write("\t\t<div class=\"bird bird--four\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("  <div class=\"bird-container bird-container--five\">\r\n");
      out.write("\t\t<div class=\"bird bird--five\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- <div class=\"imag\">\r\n");
      out.write("\t<img id=\"im\" src=\"resources/white.jpg\" />\r\n");
      out.write("</div> -->\r\n");
      out.write("<div class=\"img2\">\r\n");
      out.write("\t<img id=\"image\" src=\"resources/scb.jpg\" />\r\n");
      out.write("</div>\r\n");
      out.write("<form method=\"post\" action=\"test/Swift-Text\" enctype=\"application/x-www-form-urlencoded\">\r\n");
      out.write("\t<div class=\"form\">\r\n");
      out.write("\t\t<fieldset>\r\n");
      out.write("\t\t\t<legend style=\"text-align:center\"><strong>Sender Details</strong></legend>\r\n");
      out.write("\t\t\t<table align=\"center\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td> <label for=\"SCountryName\">Country Name </label></td>\r\n");
      out.write("\t\t\t\t\t<td>  <select id = \"country\" name=\"country\" onchange=\"updateBank(this)\" required>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"\" >Select one country</option>\r\n");
      out.write("\t\t\t\t\t\t</select>  </td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><label for=\"sendBank\">Bank Name</label></td>\r\n");
      out.write("\t\t\t\t\t<td>  <select id = \"bank\" name=\"bank\" onchange=\"updateBank(this)\" required>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"\">Select one bank</option>\r\n");
      out.write("\t\t\t\t\t\t</select>  </td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>  <label for=\"SCityName\">City</label></td>\r\n");
      out.write("\t\t\t\t\t<td>  <select id = \"city\" name=\"city\" onchange=\"updateBank(this)\" required>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"\">Select one city</option>\r\n");
      out.write("\t\t\t\t\t\t</select>  </td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>  <label for=\"SBranch\"> Branch   </label></td>\r\n");
      out.write("\t\t\t\t\t<td>  <select id = \"branch\" name=\"branch\" onchange=\"updateBank(this)\" required>\r\n");
      out.write("\t\t\t\t\t<option value=\"\">Select one branch</option>\r\n");
      out.write("\t\t\t\t\t</select> </td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</fieldset>\r\n");
      out.write("\t <br>\r\n");
      out.write("\t <fieldset>\r\n");
      out.write("\t\t<legend style=\"text-align:center\"><strong>Application Details</strong></legend>\r\n");
      out.write("\t\t<table align=\"center\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><label>Option</label></td>\r\n");
      out.write("\t\t\t\t<td><select class=\"dropdown\" id=\"direction\" name=\"direction\" required>\r\n");
      out.write("\t\t\t\t<option value=\"\">Select</option>\r\n");
      out.write("\t\t\t\t<option value=\"I\">Input</option>\r\n");
      out.write("\t\t\t\t<option value=\"O\">Output</option>\r\n");
      out.write("\t\t\t\t</select> </td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><label>Message Type</label></td>\r\n");
      out.write("\t\t\t\t<td><select class=\"dropdown\" id = \"MT\" name=\"MT\" required>\r\n");
      out.write("\t\t\t\t<option value=\"\">Select</option>\r\n");
      out.write("\t\t\t\t<option value=\"540\">MT540</option>\r\n");
      out.write("\t\t\t\t<option value=\"542\">MT542</option>\r\n");
      out.write("\t\t\t\t</select> </td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t </fieldset>\r\n");
      out.write("\t <br>\r\n");
      out.write("\t <fieldset>\r\n");
      out.write("\t\t<legend style=\"text-align:center\"><strong>Receiver Details</strong></legend>\r\n");
      out.write("\t\t<table align=\"center\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td> <label for=\"RCountryName\">Country Name </label></td>\r\n");
      out.write("\t\t\t\t\t<td>  <select id = \"Country\" name=\"Country\" onchange=\"updateBank(this)\" required>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"\">Select one country</option>\r\n");
      out.write("\t\t\t\t\t\t</select>  </td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><label for=\"recieveBank\">Bank Name</label></td>\r\n");
      out.write("\t\t\t\t\t<td>  <select id = \"Bank\" name=\"Bank\" onchange=\"updateBank(this)\" required>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"\">Select one bank</option>\r\n");
      out.write("\t\t\t\t\t\t</select>  </td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>  <label for=\"RCityName\">City</label></td>\r\n");
      out.write("\t\t\t\t\t<td>  <select id = \"City\" name=\"City\" onchange=\"updateBank(this)\" required>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"\">Select one city</option>\r\n");
      out.write("\t\t\t\t\t\t</select>  </td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>  <label for=\"RBranch\">Branch   </label></td>\r\n");
      out.write("\t\t\t\t\t<td>  <select id = \"Branch\" name=\"Branch\" onchange=\"updateBank(this)\" required>\r\n");
      out.write("\t\t\t\t\t<option value=\"\">Select one branch</option>\r\n");
      out.write("\t\t\t\t\t</select> </td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>  <label> Message Priority</label></td>\r\n");
      out.write("\t\t\t\t\t<td>  <select name=\"msgPriority\">\r\n");
      out.write("\t\t\t\t\t<option value=\"U\">U</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"N\">N</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"S\">S</option>\r\n");
      out.write("\t\t\t\t\t</select> </td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t </fieldset>\r\n");
      out.write("\t \t<select id = \"swiftcode\" name = \"swiftcode\" style=\"display: none\"></select>\r\n");
      out.write("\t \t<select id = \"Swiftcode\" name = \"Swiftcode\" style=\"display: none\"></select>\r\n");
      out.write("\t <br>\r\n");
      out.write("\t\t<div class=\"wrapper\">\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"SUBMIT\"/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
